# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: fr
    locales: en|fr
    files_directory: '%kernel.project_dir%/public'

services:
    # default configuration for services in *this* file
    _defaults:
        public: true
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Form/Transformer/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%files_directory%'
            
    #sonata admin services
    admin.region:
        class: App\Admin\RegionAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Region, group: Localisation, icon: 'fas fa-location-arrow',  manager_type: orm, label: Regions }
        calls:
            - [addChild, ['@admin.departement', 'region']]
            - [setTranslationDomain, ['App']]

    admin.departement:
        class: App\Admin\DepartementAdmin
        calls:
            - [setTranslationDomain, ['App']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Departement, manager_type: orm, group: Localisation, label: Departement }

    admin.club:
        class: App\Admin\ClubAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Club, group: Clubs, icon: 'fab fa-artstation',  manager_type: orm, label: Clubs }
        calls:
            - [addChild, ['@admin.clubstade', 'club']]
            - [addChild, ['@admin.affiliation', 'club']]
            - [addChild, ['@admin.insurance', 'club']]
            - [setTranslationDomain, ['App']]
    
    admin.clubstade:
        class: App\Admin\ClubStadeAdmin
        calls:
            - [setTranslationDomain, ['App']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\ClubStade, manager_type: orm, group: Clubs, label: Clubs et Stades }

    
    admin.stade:
        class: App\Admin\StadeAdmin
        calls:
            - [setTranslationDomain, ['App']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Stade, manager_type: orm, group: Clubs, label: Stades }

    admin.affiliation:
        class: App\Admin\AffiliationAdmin
        calls:
            - [setTranslationDomain, ['App']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Affiliation, manager_type: orm, group: Clubs, label: Affiliations }

    
    admin.discipline:
        class: App\Admin\DisciplineAffinitaireAdmin
        calls:
            - [setTranslationDomain, ['App']]
            - [addChild, ['@admin.discipline_regles', 'discipline']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\DisciplineAffinitaire, manager_type: orm, icon: 'fas fa-passport', group: Discipline Affinitaire, label: Disciplines }

    admin.regle:
        class: App\Admin\RegleAdmin
        calls:
            - [setTranslationDomain, ['App']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Regle, manager_type: orm, group: Discipline Affinitaire, label: Regles }


    admin.personnel:
        class: App\Admin\PersonnelAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Personnel, group: Acteurs, icon: 'fas fa-users-cog',  manager_type: orm, label: Personnes }
        calls:
            - [addChild, ['@admin.personnel_position', 'personnel']]
            - [addChild, ['@admin.licence', 'personnel']]
            - [addChild, ['@admin.diplome', 'personne']]
            - [addChild, ['@admin.aptitude', 'personne']]
            - [addChild, ['@admin.contrat', 'personnel']]
            - [setTranslationDomain, ['App']]

    admin.licence:
        class: App\Admin\LicenceAdmin
        calls:
            - [setTranslationDomain, ['App']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Licence, manager_type: orm, group: Acteurs, label: Licences }


    admin.contrat:
        class: App\Admin\ContratAdmin
        calls:
            - [setTranslationDomain, ['App']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Contrat, manager_type: orm, group: Acteurs, label: Contrat }

    admin.diplome:
        class: App\Admin\DiplomeAdmin
        calls:
            - [setTranslationDomain, ['App']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Diplome, manager_type: orm, group: Acteurs, label: Diplome }

    admin.aptitude:
        class: App\Admin\CertificatAptitudeAdmin
        calls:
            - [setTranslationDomain, ['App']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\CertificatAptitude, manager_type: orm, group: Acteurs, label: Certificat Aptitude }
    
    admin.insurance:
        class: App\Admin\InsuranceAdmin
        calls:
            - [setTranslationDomain, ['App']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Insurance, manager_type: orm, group: Acteurs, label: Assurance }

    admin.position:
        class: App\Admin\PositionAdmin
        calls:
            - [setTranslationDomain, ['App']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Position, manager_type: orm, group: Acteurs, label: Positions }

    admin.personnel_position:
        class: App\Admin\PersonnelPositionAdmin
        calls:
            - [setTranslationDomain, ['App']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\PersonnelPosition, manager_type: orm, group: Acteurs, label: Personnes et Position }
    
    admin.discipline_regles:
        class: App\Admin\DisciplineReglesAdmin
        calls:
            - [setTranslationDomain, ['App']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\DisciplineRegles, manager_type: orm, group: Discipline Affinitaire, label: Disciplines et regles }

    admin.bureau:
        class: App\Admin\BureauAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Bureau, group: Bureaux, icon: 'fas fa-cash-register',  manager_type: orm, label: Bureaux }
        calls:
            - [setTranslationDomain, ['App']]
            - [addChild, ['@admin.bureau_personnes', 'bureau']]

    admin.bureau_position:
        class: App\Admin\BureauPositionAdmin
        calls:
            - [setTranslationDomain, ['App']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\BureauPosition, manager_type: orm, group: Bureaux, label: Bureaux et Positions }

    admin.bureau_personnes:
        class: App\Admin\BureauPersonnesAdmin
        calls:
            - [setTranslationDomain, ['App']]
        tags:
            - { name: sonata.admin, model_class: App\Entity\BureauPersonnes, manager_type: orm, group: Bureaux, label: Bureaux et Personnes }

    admin.saison:
        class: App\Admin\SaisonAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Saison, group: Saison, icon: 'fas fa-users-cog',  manager_type: orm, label: Saisons }
        calls:
            - [addChild, ['@admin.affiliation', 'saison']]
            - [addChild, ['@admin.licence', 'saison']]
            - [setTranslationDomain, ['App']]

    admin.league:
        class: App\Admin\LeagueAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\League, controller: ~, manager_type: orm, group: Saison, label: Ligues }
        calls:
            - [addChild, ['@admin.club', 'league']]
            - [setTranslationDomain, ['App']]